# Generated by Django 4.1.1 on 2022-09-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomnumbermodel',
            name='random_number',
            field=models.IntegerField(default=45642),
        ),
    ]
